import { DeviationPlay } from '../types';

/**
 * The Illustrious 18 — the most important index plays for Hi-Lo.
 * Developed by Don Schlesinger in "Blackjack Attack".
 * These 18 plays capture ~85% of the gain from all possible index plays.
 * Indices are for Hi-Lo true count; multiply by system's betting correlation for others.
 *
 * Ordered by importance (gain in expected value).
 */
export const ILLUSTRIOUS_18: DeviationPlay[] = [
  {
    id: 'i18-1',
    name: 'Insurance',
    handType: 'hard',
    playerHand: 'any',
    dealerUpcard: 'A',
    normalAction: 'H', // normally don't take insurance
    deviationAction: 'S', // take insurance
    index: 3,
    direction: '>=',
    category: 'illustrious18',
    description: 'Take insurance when TC ≥ +3. This is the single most valuable index play.',
  },
  {
    id: 'i18-2',
    name: '16 vs 10: Stand',
    handType: 'hard',
    playerHand: '16',
    dealerUpcard: '10',
    normalAction: 'H',
    deviationAction: 'S',
    index: 0,
    direction: '>=',
    category: 'illustrious18',
    description: 'Stand on 16 vs 10 when TC ≥ 0 (instead of hitting).',
  },
  {
    id: 'i18-3',
    name: '15 vs 10: Stand',
    handType: 'hard',
    playerHand: '15',
    dealerUpcard: '10',
    normalAction: 'H',
    deviationAction: 'S',
    index: 4,
    direction: '>=',
    category: 'illustrious18',
    description: 'Stand on 15 vs 10 when TC ≥ +4.',
  },
  {
    id: 'i18-4',
    name: 'TT vs 5: Split',
    handType: 'pair',
    playerHand: 'TT',
    dealerUpcard: '5',
    normalAction: 'S',
    deviationAction: 'P',
    index: 5,
    direction: '>=',
    category: 'illustrious18',
    description: 'Split tens vs 5 when TC ≥ +5.',
  },
  {
    id: 'i18-5',
    name: 'TT vs 6: Split',
    handType: 'pair',
    playerHand: 'TT',
    dealerUpcard: '6',
    normalAction: 'S',
    deviationAction: 'P',
    index: 4,
    direction: '>=',
    category: 'illustrious18',
    description: 'Split tens vs 6 when TC ≥ +4.',
  },
  {
    id: 'i18-6',
    name: '10 vs 10: Double',
    handType: 'hard',
    playerHand: '10',
    dealerUpcard: '10',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 4,
    direction: '>=',
    category: 'illustrious18',
    description: 'Double hard 10 vs 10 when TC ≥ +4.',
  },
  {
    id: 'i18-7',
    name: '12 vs 3: Stand',
    handType: 'hard',
    playerHand: '12',
    dealerUpcard: '3',
    normalAction: 'H',
    deviationAction: 'S',
    index: 2,
    direction: '>=',
    category: 'illustrious18',
    description: 'Stand on 12 vs 3 when TC ≥ +2.',
  },
  {
    id: 'i18-8',
    name: '12 vs 2: Stand',
    handType: 'hard',
    playerHand: '12',
    dealerUpcard: '2',
    normalAction: 'H',
    deviationAction: 'S',
    index: 3,
    direction: '>=',
    category: 'illustrious18',
    description: 'Stand on 12 vs 2 when TC ≥ +3.',
  },
  {
    id: 'i18-9',
    name: '11 vs A: Double',
    handType: 'hard',
    playerHand: '11',
    dealerUpcard: 'A',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 1,
    direction: '>=',
    category: 'illustrious18',
    description: 'Double 11 vs Ace when TC ≥ +1.',
  },
  {
    id: 'i18-10',
    name: '9 vs 2: Double',
    handType: 'hard',
    playerHand: '9',
    dealerUpcard: '2',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 1,
    direction: '>=',
    category: 'illustrious18',
    description: 'Double hard 9 vs 2 when TC ≥ +1.',
  },
  {
    id: 'i18-11',
    name: '10 vs A: Double',
    handType: 'hard',
    playerHand: '10',
    dealerUpcard: 'A',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 4,
    direction: '>=',
    category: 'illustrious18',
    description: 'Double hard 10 vs Ace when TC ≥ +4.',
  },
  {
    id: 'i18-12',
    name: '9 vs 7: Double',
    handType: 'hard',
    playerHand: '9',
    dealerUpcard: '7',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 3,
    direction: '>=',
    category: 'illustrious18',
    description: 'Double hard 9 vs 7 when TC ≥ +3.',
  },
  {
    id: 'i18-13',
    name: '16 vs 9: Stand',
    handType: 'hard',
    playerHand: '16',
    dealerUpcard: '9',
    normalAction: 'H',
    deviationAction: 'S',
    index: 5,
    direction: '>=',
    category: 'illustrious18',
    description: 'Stand on 16 vs 9 when TC ≥ +5.',
  },
  {
    id: 'i18-14',
    name: '13 vs 2: Hit',
    handType: 'hard',
    playerHand: '13',
    dealerUpcard: '2',
    normalAction: 'S',
    deviationAction: 'H',
    index: -1,
    direction: '<=',
    category: 'illustrious18',
    description: 'Hit 13 vs 2 when TC ≤ -1 (instead of standing).',
  },
  {
    id: 'i18-15',
    name: '12 vs 4: Hit',
    handType: 'hard',
    playerHand: '12',
    dealerUpcard: '4',
    normalAction: 'S',
    deviationAction: 'H',
    index: 0,
    direction: '<=',
    category: 'illustrious18',
    description: 'Hit 12 vs 4 when TC ≤ 0 (instead of standing).',
  },
  {
    id: 'i18-16',
    name: '12 vs 5: Hit',
    handType: 'hard',
    playerHand: '12',
    dealerUpcard: '5',
    normalAction: 'S',
    deviationAction: 'H',
    index: -2,
    direction: '<=',
    category: 'illustrious18',
    description: 'Hit 12 vs 5 when TC ≤ -2.',
  },
  {
    id: 'i18-17',
    name: '12 vs 6: Hit',
    handType: 'hard',
    playerHand: '12',
    dealerUpcard: '6',
    normalAction: 'S',
    deviationAction: 'H',
    index: -1,
    direction: '<=',
    category: 'illustrious18',
    description: 'Hit 12 vs 6 when TC ≤ -1.',
  },
  {
    id: 'i18-18',
    name: '13 vs 3: Hit',
    handType: 'hard',
    playerHand: '13',
    dealerUpcard: '3',
    normalAction: 'S',
    deviationAction: 'H',
    index: -2,
    direction: '<=',
    category: 'illustrious18',
    description: 'Hit 13 vs 3 when TC ≤ -2.',
  },
];

/**
 * The Fab 4 Surrender plays — the four most important surrender deviations.
 * Also from Don Schlesinger's "Blackjack Attack".
 */
export const FAB_4: DeviationPlay[] = [
  {
    id: 'fab4-1',
    name: '14 vs 10: Surrender',
    handType: 'hard',
    playerHand: '14',
    dealerUpcard: '10',
    normalAction: 'H',
    deviationAction: 'Rh',
    index: 3,
    direction: '>=',
    category: 'fab4',
    description: 'Surrender 14 vs 10 when TC ≥ +3.',
  },
  {
    id: 'fab4-2',
    name: '15 vs 9: Surrender',
    handType: 'hard',
    playerHand: '15',
    dealerUpcard: '9',
    normalAction: 'H',
    deviationAction: 'Rh',
    index: 2,
    direction: '>=',
    category: 'fab4',
    description: 'Surrender 15 vs 9 when TC ≥ +2.',
  },
  {
    id: 'fab4-3',
    name: '15 vs A: Surrender',
    handType: 'hard',
    playerHand: '15',
    dealerUpcard: 'A',
    normalAction: 'H',
    deviationAction: 'Rh',
    index: 1,
    direction: '>=',
    category: 'fab4',
    description: 'Surrender 15 vs Ace when TC ≥ +1.',
  },
  {
    id: 'fab4-4',
    name: '14 vs A: Surrender',
    handType: 'hard',
    playerHand: '14',
    dealerUpcard: 'A',
    normalAction: 'H',
    deviationAction: 'Rh',
    index: 7,
    direction: '>=',
    category: 'fab4',
    description: 'Surrender 14 vs Ace when TC ≥ +7.',
  },
];

/**
 * Additional deviation plays beyond the Illustrious 18 and Fab 4.
 * These provide smaller but still meaningful gains.
 */
export const ADDITIONAL_DEVIATIONS: DeviationPlay[] = [
  {
    id: 'add-1',
    name: 'TT vs 4: Split',
    handType: 'pair',
    playerHand: 'TT',
    dealerUpcard: '4',
    normalAction: 'S',
    deviationAction: 'P',
    index: 6,
    direction: '>=',
    category: 'additional',
    description: 'Split tens vs 4 when TC ≥ +6.',
  },
  {
    id: 'add-2',
    name: '8 vs 6: Double',
    handType: 'hard',
    playerHand: '8',
    dealerUpcard: '6',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 2,
    direction: '>=',
    category: 'additional',
    description: 'Double 8 vs 6 when TC ≥ +2.',
  },
  {
    id: 'add-3',
    name: '8 vs 5: Double',
    handType: 'hard',
    playerHand: '8',
    dealerUpcard: '5',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 3,
    direction: '>=',
    category: 'additional',
    description: 'Double 8 vs 5 when TC ≥ +3.',
  },
  {
    id: 'add-4',
    name: '14 vs 10: Stand',
    handType: 'hard',
    playerHand: '14',
    dealerUpcard: '10',
    normalAction: 'H',
    deviationAction: 'S',
    index: 8,
    direction: '>=',
    category: 'additional',
    description: 'Stand on 14 vs 10 when TC ≥ +8 (extremely rare).',
  },
  {
    id: 'add-5',
    name: 'A2 vs 5: Double',
    handType: 'soft',
    playerHand: 'A2',
    dealerUpcard: '5',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: -1,
    direction: '>=',
    category: 'additional',
    description: 'Double soft 13 (A2) vs 5 when TC ≥ -1.',
  },
  {
    id: 'add-6',
    name: 'A6 vs 2: Double',
    handType: 'soft',
    playerHand: 'A6',
    dealerUpcard: '2',
    normalAction: 'H',
    deviationAction: 'Dh',
    index: 1,
    direction: '>=',
    category: 'additional',
    description: 'Double soft 17 (A6) vs 2 when TC ≥ +1.',
  },
  {
    id: 'add-7',
    name: 'A7 vs 2: Double',
    handType: 'soft',
    playerHand: 'A7',
    dealerUpcard: '2',
    normalAction: 'S',
    deviationAction: 'Ds',
    index: 1,
    direction: '>=',
    category: 'additional',
    description: 'Double soft 18 (A7) vs 2 when TC ≥ +1.',
  },
  {
    id: 'add-8',
    name: '11 vs 10: Double',
    handType: 'hard',
    playerHand: '11',
    dealerUpcard: '10',
    normalAction: 'Dh',
    deviationAction: 'H',
    index: -3,
    direction: '<=',
    category: 'additional',
    description: 'Just hit (don\'t double) 11 vs 10 when TC ≤ -3.',
  },
  {
    id: 'add-9',
    name: '15 vs 10: Surrender',
    handType: 'hard',
    playerHand: '15',
    dealerUpcard: '10',
    normalAction: 'Rh',
    deviationAction: 'H',
    index: 0,
    direction: '<=',
    category: 'additional',
    description: 'Don\'t surrender 15 vs 10 when TC ≤ 0 (just hit instead).',
  },
  {
    id: 'add-10',
    name: 'TT vs A: Split',
    handType: 'pair',
    playerHand: 'TT',
    dealerUpcard: 'A',
    normalAction: 'S',
    deviationAction: 'P',
    index: 8,
    direction: '>=',
    category: 'additional',
    description: 'Split tens vs Ace when TC ≥ +8 (very high count).',
  },
];

export const ALL_DEVIATIONS: DeviationPlay[] = [
  ...ILLUSTRIOUS_18,
  ...FAB_4,
  ...ADDITIONAL_DEVIATIONS,
];

/**
 * Get active deviations based on current true count
 */
export function getActiveDeviations(
  trueCount: number,
  surrenderAvailable: boolean,
): DeviationPlay[] {
  return ALL_DEVIATIONS.filter(dev => {
    // Skip surrender plays if surrender not available
    if (!surrenderAvailable && (dev.deviationAction === 'Rh' || dev.deviationAction === 'Rs' || dev.deviationAction === 'Rp')) {
      return false;
    }

    if (dev.direction === '>=') {
      return trueCount >= dev.index;
    } else {
      return trueCount <= dev.index;
    }
  });
}

/**
 * Check if a specific hand/dealer combo has an active deviation
 */
export function getDeviation(
  playerHand: string,
  dealerUpcard: string,
  trueCount: number,
  surrenderAvailable: boolean,
): DeviationPlay | null {
  const active = getActiveDeviations(trueCount, surrenderAvailable);
  return active.find(d =>
    d.playerHand === playerHand && d.dealerUpcard === dealerUpcard
  ) ?? null;
}
